---
commonLabels:
  app: cartography
  component: cartography-elastic-ingestor

resources:
  - ingestor-cronjob.yaml

configMapGenerator:
  - name: cartography-elastic-index-configmap
    files:
      - es-index.json
