name: '[DOCKER IMAGE] Cartography Queries'

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'consumers/elasticsearch/docker/**/*'
      - 'queries/queries.json'
  pull_request:
    branches:
      - main
    paths:
      - 'consumers/elasticsearch/docker/**/*'
      - 'queries/queries.json'

jobs:
  run-docker:
    permissions:
      id-token: write
      contents: read
      pull-requests: write

    uses: marco-lancini/cartography-queries/.github/workflows/reusable-docker.yml@main
    with:
      FOLDER: ${{ github.workspace }}/queries
      REGISTRY: ghcr.io/${{ github.repository_owner }}
      IMAGE_NAME: cartography_queries
