name: '[DOCKER IMAGE] Cartography Elasticsearch Ingestor'

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'consumers/elasticsearch/docker/**/*'
      - 'queries/queries.json'
  pull_request:
    branches:
      - main
    paths:
      - 'consumers/elasticsearch/docker/**/*'
      - 'queries/queries.json'

jobs:
  run-docker:
    permissions:
      id-token: write
      contents: read
      pull-requests: write

    uses: marco-lancini/cartography-queries/.github/workflows/reusable-docker.yml@main
    with:
      FOLDER: ${{ github.workspace }}/consumers/elasticsearch/docker
      REGISTRY: ghcr.io/${{ github.repository_owner }}
      IMAGE_NAME: cartography_elastic_ingestor
    secrets:
      GHCR_USER: ${{ github.repository_owner }}
      GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}
